# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.17.1
loader_version=0.16.14
loom_version=1.10-SNAPSHOT

# Mod Properties
mod_version=4.0.0-Fabric-1.17.1
maven_group=github.qingha
archives_base_name=resource-syncronization

# Dependencies
fabric_version=0.46.1+1.17